# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check Canary Build

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    
permissions:
  contents: write

jobs:
  fetch-files:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        npm install
    
    - name: Fetch Files
      run: |
        npm run canary

    - name: Commit to the repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m 'New Canary Build' || true
        git push